# Generated by Django 6.1 on 2026-09-20 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('location', models.CharField(default='Sector 7 Class-1 Cleanroom, Aether Biometrix', max_length=200)),
                ('min_evidence_required', models.IntegerField(default=4)),
                ('total_evidence', models.IntegerField(default=6)),
                ('initial_node_id', models.CharField(default='scene_1_intro', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('clue_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('inference', models.TextField()),
                ('contradiction', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='file', max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='investigation.case')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueNode',
            fields=[
                ('node_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scene_number', models.IntegerField(default=1)),
                ('background', models.CharField(default='bg_cleanroom_int', max_length=100)),
                ('speaker', models.CharField(max_length=100)),
                ('sprite', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('audio_cue', models.CharField(blank=True, max_length=50, null=True)),
                ('clue_unlock', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_delta', models.IntegerField(default=0)),
                ('choices_json', models.JSONField(blank=True, default=list)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_nodes', to='investigation.case')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy', models.IntegerField(default=100)),
                ('unlocked_clues', models.JSONField(blank=True, default=list)),
                ('current_node_id', models.CharField(default='scene_1_intro', max_length=100)),
                ('detective_gender', models.CharField(default='f', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('game_over', 'Game Over'), ('solved', 'Solved')], default='active', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='investigation.case')),
            ],
        ),
    ]
