# Generated by Django 6.1 on 2026-09-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
