# Generated by Django 6.1 on 2026-09-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_gamesession_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='visited_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
