# Generated by Django 6.1 on 2026-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0003_gamesession_visited_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='energy',
            field=models.IntegerField(default=50),
        ),
    ]
