# Generated by Django 6.1 on 2026-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0004_alter_gamesession_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='min_evidence_required',
            field=models.IntegerField(default=2),
        ),
    ]
