# Generated by Django 6.1 on 2026-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0005_alter_case_min_evidence_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='min_evidence_required',
            field=models.IntegerField(default=3),
        ),
    ]
